### ISSUE TITLE
New docker image with Java 13 ShenandoahGC ready

### ISSUE THREAD

**Issue by SrBedrock** [parkervcp/images#38]
Hi guys, thanks for this open source project!
Very well documented, even without understanding linux I was able to install my panel easily.

I'm hosting Minecraft 1.15.2 and apparently the use of garbage collectors like ShenandoahGC has proven to be superior to G1GC in this version.

After several searches I found that unfortunately the java version made available by Oracle (openjdk 11, 12 and 13) does not come with the option enabled.

[The reason is explained here.](https://developers.redhat.com/blog/2019/04/19/not-all-openjdk-12-builds-include-shenandoah-heres-why/).

[Project page with all relevant information ](https://wiki.openjdk.java.net/display/shenandoah/Main#Main-JDKSupport)

Could you help me install a compatible docker image?

I really tried to create a dockerfile but due to lack of knowledge I couldn't.

[I was trying to install this java 13 which is compatible according to the project instructions.](https://hub.docker.com/layers/shipilev/openjdk/13/images/sha256-baaa3135aebfcd524ebf0dd06201f1c3c518ed9d751196547e074440b52cc8cd?context=explore)

Thanks parker!

**Comment by parkervcp** [comment]
I have a new branch and this should be resolved by 027d1e8

**Comment by parkervcp** [comment]
@SrBedrock if you would try that out
