### ISSUE TITLE
Bad time in container (-1h)

### ISSUE THREAD

**Issue by ryrzy** [parkervcp/images#76]
Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 1.2.2
Daemon Version: 1.2.3
Service: RUST
Docker Image: Docker version 20.10.3, build 48d30b5
Modified: no

Errors that you are experiencing:

problem is with time on containers, everything is set ok on host but still i have -1H on containers. I think the problem is that there is no /etc/timezone file (or link from host /etc/timezone). My configs looks like this:

**HOST time:**

`root@xxx ~ # timedatectl
               Local time: Tue 2021-02-23 10:48:12 CET
           Universal time: Tue 2021-02-23 09:48:12 UTC
                 RTC time: Tue 2021-02-23 09:48:12
                Time zone: Europe/Warsaw (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no`
          
**pterodactyl env:**

`APP_TIMEZONE=Europe/Warsaw`

**container has TZ ok:**

 `           "Env": [
                "TZ=Europe/Warsaw",`

**container time:**

`root@xxx ~ # docker exec -it d9e4xxxxxc0 date
Tue Feb 23 09:51:05 Europe 2021`

**tzselect on contaner:**

`root@dcxxx0-68ab-4xx1-a0ca-xxxx6:/etc# tzselect
/usr/bin/tzselect: line 180: /usr/share/zoneinfo/iso3166.tab: No such file or directory
/usr/bin/tzselect: time zone files are not set up correctly`

there is always -1h, it shows UTC time not local GMT+1

**Comment by ryrzy** [comment]
bump

**Comment by trenutoo** [comment]
This[ pull request](https://github.com/pterodactyl/images/pull/76) resolves the issue

**Comment by ryrzy** [comment]
it looks ok now! thank you

**Comment by r4sas** [comment]
@parkervcp, I think we must add tzdata in all images. I have same problem with ubuntu_source image.

**Comment by parkervcp** [comment]
> @parkervcp, I think we must add tzdata in all images. I have same problem with ubuntu_source image.

We are moving to the yolks repo. You should be using those images.

**Comment by r4sas** [comment]
> > @parkervcp, I think we must add tzdata in all images. I have same problem with ubuntu_source image.
> 
> We are moving to the yolks repo. You should be using those images.

How I can migrate to yolks repo from old one (without full reinstall of server, if possible)?

**Comment by parkervcp** [comment]
> > > @parkervcp, I think we must add tzdata in all images. I have same problem with ubuntu_source image.
> > 
> > 
> > We are moving to the yolks repo. You should be using those images.
> 
> How I can migrate to yolks repo from old one?

You literally just use the image from the yolks repo. All the eggs are getting updated for it.

**Comment by r4sas** [comment]
Got it, thank you.
I'll try to add `ghcr.io/parkervcp/games:source` to current egg and try to start server.
