### ISSUE TITLE
Node.js v15 and Python 3.9 image

### ISSUE THREAD

**Issue by NoodlesDev987** [parkervcp/images#83]
Add support for node.js v15 to discord.js egg, and python 3.9 to discord.py egg.

**Comment by trenutoo** [comment]
Python 3.9 image already exists and is within this repository. You can also find it on [quay](https://quay.io/repository/parkervcp/pterodactyl-images?tag=latest&tab=tags) from where you can add it to your egg

**Comment by trenutoo** [comment]
Resolved in #84 and https://github.com/parkervcp/eggs/pull/1212
